import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from '@/components/shared/Navbar/Navbar'
import Footer from '@/components/shared/Footer/Footer'
import { ParticleComponent } from '@/lib/particles'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blokminers',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
